name: Fix NPM Tags

on:
  workflow_dispatch: 

jobs:
  fix-tags:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4.0.3
        with:
          node-version: 20.x
          registry-url: "https://registry.npmjs.org/"
      
      - name: Fix dist-tags
        run: |
          npm dist-tag add tkeron@3.8.0 latest
          npm dist-tag add tkeron@4.0.0-alpha.1 alpha
          npm dist-tag add tkeron@4.0.0-alpha.2 alpha
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      - name: Verify tags
        run: npm dist-tag ls tkeron
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
